### ISSUE TITLE
Commands missing from API-async

### ISSUE THREAD

**Issue by MightyMaxSaviorOfTheUniverse** [harwee/IQOption-Api#45]
Hello again, I hope you are doing well, you are certainly treating us kindly with this program of yours

I noticed that the following commands for the API-async are **missing**

Check Account Balance

    print(api.active_balance_id) # Prints the active balance id

Check Active Account Balance

    balance_id = api.active_balance_id
    balance_object = api.balances[balance_id]
    print(balance_object["amount"]) # prints active account balance

Attributes of BinaryOption
EURUSD = iqoption.options["binary"]["EURUSD"]
print(EURUSD.type)
print(EURUSD.first_candle)

These commands don't work because they are made for IQOption-Api-master. There is also no way to run the following code on API-async

Check Account Type

    print(api.active_account) # prints `real` or `practice`

Change Account

    api.change_account("real") # `real` or `practice` Returns Account Type (`real` or `practice`)

Check Positions Modified/Opened After API Started

    print(api.positions)  

Get Instruments

    print(api.instruments_to_id) ## All Instruments Websocket Returned
    print(api.forex_instruments)
    print(api.cfd_instruments)
    print(api.crypto_instruments)

Please provide an alternative means of generating the same results for the new API-async, and update your examples on the API-async main page.

A further request if I may:

There seems to be no way to get the incoming profit from Instruments but I see in the code when you place an order, it tells you the incoming profit. Is there any way to extract that data before placing an order?

Thank you in advance

**Comment by harwee** [comment]
`active_balance_id, balances[balance_id], active_account, positions, instruments_to_id, forex_instruments, cfd_instruments, crypto_instruments` are all instance attributes of a class, they do not invoke any api calls and are served from already existing data, so accessing them is near instantaneous and you don not require `async` since they are not methods but attributes

In async api you have to change account using `await iqoption.change_balance(balance_id)` instead of `change_account("real")` since there can be many balances instead of just one `real` and `practice`
